{
    'name': 'Catering Management',
    'version': '16.0.2.0.0',
    'summary': """Core Module for Managing Different Types Of Events.""",
    'description': """modul untuk catering industri menyambungkan ke incentory manegement """,
    "category": "Services",
    'author': 'DIKI ILHAM FIRMASNYAH',
    'company': 'Telkom University',
    'maintainer': 'DIKI ILHAM FIRMASNYAH',
    'website': "https://diki1211.blogspot.com/",
    'depends': ['product', 'account'],
    'data': ['security/event_security.xml',
             'security/ir.model.access.csv',
             'views/event_management_view.xml',
             'views/event_type_view.xml',
             'views/dashboard.xml',
             'data/event_management.xml',
             'reports/event_management_pdf_report.xml',
             'reports/pdf_report_template.xml',
             'wizards/event_management_wizard.xml',
             ],
    'assets': {
        'web.assets_backend': [
            "event_management/static/src/css/event_dashboard.css",
            "event_management/static/src/js/action_manager.js"
        ],
    },
    'images': ['static/description/banner.png'],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
}
