{
    'name': 'Event Catering Service',
    'version': '16.0.2.0.0',
    'summary': """Catering Service for Event Management Module.""",
    'description': """ sub modul dari Catering management  untuk service.""",
    "category": "Industry",
    'author': 'DIKI ILHAM FIRMASNYAH',
    'company': 'Telkom University',
    'maintainer': 'DIKI ILHAM FIRMASNYAH',
    'website': "https://diki1211.blogspot.com/",
    'depends': ['event_management'],
    'data': ['security/catering_security.xml',
             'security/ir.model.access.csv',
             'views/catering_service.xml',
             'views/event_form.xml',
             'views/product_product_views.xml',
             'data/catering_service.xml',
             ],
    'demo': [
    ],
    'images': ['static/description/banner.png'],
    'license': 'AGPL-3',
    'installable': True,
    'application': False,
}
